---

- name: Remove old Docker versions
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - docker-engine
      - containerd
      - docker.io
      - runc

- name: Install required apt pkgs
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker repo
  apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable" state=present update_cache=yes

- name: Install Docker
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
